version: "3.4"

services:
  exporter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - exporter:/app
    container_name: exporter
volumes:
  exporter: