version: "3.4"

services:
  exporter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    container_name: exporter
    restart: always

networks:
  default:
    name: rh-api-network
    external: true
